id: "20260117-055655_multiple-fathom-summaries-for-rick-and-doug-plea"
title: "Multiple Fathom Summaries for Rick and Doug

Plea"
created_at: "2026-01-17T05:56:55-08:00"
completed_at: null
source: "SESSION"
status: "ACTIVE"
session_id: "cf1077a2-c4ff-416e-9061-ea750b4d5a11"
lineage:
  tools_used: []
  files_changed: []
  agents_spawned: []
parent: null
