id: "20260123-204538_run-mve-extraction"
title: "Run MVE extraction"
created_at: "2026-01-23T20:45:38-08:00"
completed_at: null
source: "SESSION"
status: "ACTIVE"
session_id: "a924dfa5-a017-4eed-9b45-d7160151368f"
lineage:
  tools_used: []
  files_changed: []
  agents_spawned: []
parent: null
