id: "20260121-130927_whats-next"
title: "what's next?"
created_at: "2026-01-21T13:09:27-08:00"
completed_at: null
source: "SESSION"
status: "ACTIVE"
session_id: "f196e0ff-2791-47e3-a4f0-4c02e0540b60"
lineage:
  tools_used: []
  files_changed: []
  agents_spawned: []
parent: null
