id: "20260123-081732_create-dcm-marketing-plan-and-copy-outline"
title: "Create DCM marketing plan and copy outline"
created_at: "2026-01-23T08:17:33-08:00"
completed_at: null
source: "SESSION"
status: "ACTIVE"
session_id: "c56fde6e-8b5a-411d-a154-201b0ac83413"
lineage:
  tools_used: []
  files_changed: []
  agents_spawned: []
parent: null
