id: "20260116-201412_recipecardsmd"
title: "RecipeCards.md"
created_at: "2026-01-16T20:14:12-08:00"
completed_at: null
source: "SESSION"
status: "ACTIVE"
session_id: "07252308-2f53-4711-889b-2b1356cc174e"
lineage:
  tools_used: []
  files_changed: []
  agents_spawned: []
parent: null
