id: "20260124-113348_i-didnt-see-the-explainer-html-did-it-open"
title: "i didn't see the explainer html  did it open?"
created_at: "2026-01-24T11:33:48-08:00"
completed_at: null
source: "SESSION"
status: "ACTIVE"
session_id: "60f66e3f-f611-461e-81aa-41b7360a03cf"
lineage:
  tools_used: []
  files_changed: []
  agents_spawned: []
parent: null
