id: "20260123-111843_show-me-the-continuation-prompt"
title: "show me the continuation prompt"
created_at: "2026-01-23T11:18:43-08:00"
completed_at: null
source: "SESSION"
status: "ACTIVE"
session_id: "c56fde6e-8b5a-411d-a154-201b0ac83413"
lineage:
  tools_used: []
  files_changed: []
  agents_spawned: []
parent: null
