id: "20260123-102354_task-notification-task-idbae37f8task-id-ou"
title: "<task-notification>
<task-id>bae37f8</task-id>
<ou"
created_at: "2026-01-23T10:23:54-08:00"
completed_at: null
source: "SESSION"
status: "ACTIVE"
session_id: "c56fde6e-8b5a-411d-a154-201b0ac83413"
lineage:
  tools_used: []
  files_changed: []
  agents_spawned: []
parent: null
