id: "20260124-103754_what-can-we-do-with-these-extractions"
title: "what can we do with these extractions"
created_at: "2026-01-24T10:37:54-08:00"
completed_at: null
source: "SESSION"
status: "ACTIVE"
session_id: "60f66e3f-f611-461e-81aa-41b7360a03cf"
lineage:
  tools_used: []
  files_changed: []
  agents_spawned: []
parent: null
