id: "20260122-213231_task-notification-task-idb50bb77task-id-ou"
title: "<task-notification>
<task-id>b50bb77</task-id>
<ou"
created_at: "2026-01-22T21:32:31-08:00"
completed_at: null
source: "SESSION"
status: "ACTIVE"
session_id: "0a724dc8-1e85-4001-900d-db9b281e9158"
lineage:
  tools_used: []
  files_changed: []
  agents_spawned: []
parent: null
