id: "20260123-213306_im-not-seeing-upgrade-i-have-lower-tier-max-pla"
title: "i'm not seeing upgrade.  I have lower tier max pla"
created_at: "2026-01-23T21:33:06-08:00"
completed_at: null
source: "SESSION"
status: "ACTIVE"
session_id: "7ead6660-2fb8-426c-96ef-7380e489b453"
lineage:
  tools_used: []
  files_changed: []
  agents_spawned: []
parent: null
