id: "20260121-125520_claudeworkscratchneo4j-desktop-installsh"
title: "~/.claude/WORK/scratch/neo4j-desktop-install.sh
"
created_at: "2026-01-21T12:55:20-08:00"
completed_at: null
source: "SESSION"
status: "ACTIVE"
session_id: "59c0fd35-fc59-401e-8372-8f435cba2937"
lineage:
  tools_used: []
  files_changed: []
  agents_spawned: []
parent: null
