id: "20260121-164624_debug-xconnect-ide-server-startup-failures"
title: "Debug xConnect IDE server startup failures"
created_at: "2026-01-21T16:46:24-08:00"
completed_at: null
source: "SESSION"
status: "ACTIVE"
session_id: "566dae7e-c38a-48d3-a8cb-52aa70a79427"
lineage:
  tools_used: []
  files_changed: []
  agents_spawned: []
parent: null
