id: "20260124-101940_recomendations-im-looking-to-increase-my-usage"
title: "recomendations   im looking to increase my usage"
created_at: "2026-01-24T10:19:40-08:00"
completed_at: null
source: "SESSION"
status: "ACTIVE"
session_id: "36a2bb82-d247-4964-9fb9-42491f43a5c0"
lineage:
  tools_used: []
  files_changed: []
  agents_spawned: []
parent: null
