id: "20260124-131027_is-thee-a-way-to-see-context-usage-in-gemini-and-o"
title: "Is thee a way to see context usage in Gemini and O"
created_at: "2026-01-24T13:10:27-08:00"
completed_at: null
source: "SESSION"
status: "ACTIVE"
session_id: "36a2bb82-d247-4964-9fb9-42491f43a5c0"
lineage:
  tools_used: []
  files_changed: []
  agents_spawned: []
parent: null
