id: "20260124-102812_why-in-my-observablity-window-localhost-5172-do-i"
title: "why in my observablity window localhost 5172 do i "
created_at: "2026-01-24T10:28:12-08:00"
completed_at: null
source: "SESSION"
status: "ACTIVE"
session_id: "be79b733-89f7-4719-9f74-b85bddcbdb0b"
lineage:
  tools_used: []
  files_changed: []
  agents_spawned: []
parent: null
