id: "20260124-105113_create-placeholder-operations-manual"
title: "Create placeholder Operations manual"
created_at: "2026-01-24T10:51:13-08:00"
completed_at: null
source: "SESSION"
status: "ACTIVE"
session_id: "7d6d2a14-7406-41b4-ae19-ea40db2bd7bb"
lineage:
  tools_used: []
  files_changed: []
  agents_spawned: []
parent: null
