id: "20260123-210938_md-formating-not-landing-in-google-doc-options"
title: ".md formating not landing in google doc.  options?"
created_at: "2026-01-23T21:09:38-08:00"
completed_at: null
source: "SESSION"
status: "ACTIVE"
session_id: "dc55c965-e7dc-46ba-8394-377b4a1d3e3b"
lineage:
  tools_used: []
  files_changed: []
  agents_spawned: []
parent: null
