id: "20260122-152604_where-do-we-have-calendar-functionality"
title: "where do we have calendar functionality?"
created_at: "2026-01-22T15:26:04-08:00"
completed_at: null
source: "SESSION"
status: "ACTIVE"
session_id: "2e428706-fae4-4d46-a0e6-362a3c444fbd"
lineage:
  tools_used: []
  files_changed: []
  agents_spawned: []
parent: null
