id: "20260121-164243_generate-html-report-with-lever-concepts"
title: "Generate HTML report with lever concepts"
created_at: "2026-01-21T16:42:43-08:00"
completed_at: null
source: "SESSION"
status: "ACTIVE"
session_id: "0ff41573-4fa0-4605-8043-1ad4678429b3"
lineage:
  tools_used: []
  files_changed: []
  agents_spawned: []
parent: null
