id: "20260123-204439_how-do-i-get-haiku-key"
title: "how do I get haiku key?"
created_at: "2026-01-23T20:44:39-08:00"
completed_at: null
source: "SESSION"
status: "ACTIVE"
session_id: "7ead6660-2fb8-426c-96ef-7380e489b453"
lineage:
  tools_used: []
  files_changed: []
  agents_spawned: []
parent: null
