id: "20260123-211640_task-notification-task-idbd665datask-id-ou"
title: "<task-notification>
<task-id>bd665da</task-id>
<ou"
created_at: "2026-01-23T21:16:40-08:00"
completed_at: null
source: "SESSION"
status: "ACTIVE"
session_id: "7ead6660-2fb8-426c-96ef-7380e489b453"
lineage:
  tools_used: []
  files_changed: []
  agents_spawned: []
parent: null
