id: "20260124-095438_read-completed-task-output-files"
title: "Read completed task output files"
created_at: "2026-01-24T09:54:38-08:00"
completed_at: null
source: "SESSION"
status: "ACTIVE"
session_id: "60f66e3f-f611-461e-81aa-41b7360a03cf"
lineage:
  tools_used: []
  files_changed: []
  agents_spawned: []
parent: null
