id: "20260124-111111_yes-show-me-full-project"
title: "yes show me full project."
created_at: "2026-01-24T11:11:11-08:00"
completed_at: null
source: "SESSION"
status: "ACTIVE"
session_id: "7d6d2a14-7406-41b4-ae19-ea40db2bd7bb"
lineage:
  tools_used: []
  files_changed: []
  agents_spawned: []
parent: null
