id: "20260124-105508_why-not-do-hybrid-how-much-more-powerful-would"
title: "why not do hybrid?   how much more powerful would "
created_at: "2026-01-24T10:55:08-08:00"
completed_at: null
source: "SESSION"
status: "ACTIVE"
session_id: "60f66e3f-f611-461e-81aa-41b7360a03cf"
lineage:
  tools_used: []
  files_changed: []
  agents_spawned: []
parent: null
