id: "20260123-110729_create-interactive-design-principles-tour"
title: "Create interactive design principles tour"
created_at: "2026-01-23T11:07:29-08:00"
completed_at: null
source: "SESSION"
status: "ACTIVE"
session_id: "8402b496-1e38-4f8e-8cec-f683937ef571"
lineage:
  tools_used: []
  files_changed: []
  agents_spawned: []
parent: null
