id: "20260121-124625_evaluate-the-pipeline-process-comparing-source-to"
title: "evaluate the pipeline process comparing source to "
created_at: "2026-01-21T12:46:25-08:00"
completed_at: null
source: "SESSION"
status: "ACTIVE"
session_id: "3e2c15fd-3af8-4eed-b3a3-f6a598d4a8ff"
lineage:
  tools_used: []
  files_changed: []
  agents_spawned: []
parent: null
