id: "20260123-082700_set-up-gmail-for-bonus-prompts"
title: "Set up Gmail for bonus prompts"
created_at: "2026-01-23T08:27:00-08:00"
completed_at: null
source: "SESSION"
status: "ACTIVE"
session_id: "bcf3ee1a-0f7a-4338-bb5b-57fc08cc8cee"
lineage:
  tools_used: []
  files_changed: []
  agents_spawned: []
parent: null
