id: "20260122-165124_debug-backend-server-startup-failure"
title: "Debug backend server startup failure"
created_at: "2026-01-22T16:51:24-08:00"
completed_at: null
source: "SESSION"
status: "ACTIVE"
session_id: "566dae7e-c38a-48d3-a8cb-52aa70a79427"
lineage:
  tools_used: []
  files_changed: []
  agents_spawned: []
parent: null
