id: "20260123-102140_read-oauth-authorization-flow-output"
title: "Read OAuth authorization flow output"
created_at: "2026-01-23T10:21:40-08:00"
completed_at: null
source: "SESSION"
status: "ACTIVE"
session_id: "bcf3ee1a-0f7a-4338-bb5b-57fc08cc8cee"
lineage:
  tools_used: []
  files_changed: []
  agents_spawned: []
parent: null
